version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./cache:/app/cache
      - ./uploads:/app/uploads
    environment:
      - FLASK_DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5000
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - app-network

  celery:
    build: .
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./cache:/app/cache
    environment:
      - FLASK_DEBUG=0
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge